#!/bin/bash
echo "🚂 Railway Service ID Helper"
echo "============================"
echo ""
echo "1. Install Railway CLI (if not installed):"
echo "   curl -fsSL https://railway.app/install.sh | sh"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. List your services:"
echo "   railway services"
echo ""
echo "4. Copy the Service ID and add to GitHub Secrets:"
echo "   - Go to: https://github.com/OrDinaD/MarhrutochkaTG/settings/secrets/actions"
echo "   - Add: RAILWAY_SERVICE_ID = [your-service-id]"
echo ""
echo "Or run this to get Service ID automatically:"
echo "   railway services --json | jq -r '.[0].id'"
